### ISSUE TITLE
do_aes_decrypt() returns plain text which is having more size then the actual plain text used to encrypt. 

### ISSUE THREAD

**Issue by arihantdaga** [spaniakos/AES#17]
Step 1 . i did do_aes_encrypt().
Step 2. base64 encode the obtained cipher.

Then
on the obtained cipher i did base64_decode().
then i did do_aes_decrypt() with the base64 decode cipher and iv obtained in previous steps.
the resultint plain text obtained from this is of length 80 while the plain text used before Step 1 was only 76 characters long. 
this is causing further issues when my decoded string looks like this **{"my message"} ????**.

**Comment by spaniakos** [comment]
please sent me the code used so i can test it.
you can sent it to my e-mail spaniakos@gmail.com

thank you

**Comment by arihantdaga** [comment]
There is one more bug now.. 
Encrypting and decrypting of this message results into this-
{"temphumid":"12,12"} -> encrypt -> decrypt again -> {"temphumid":"12,12"?⸮⸮⸮
It also happens if i have 2 consecutive "}}" in the end of the string

**Comment by spaniakos** [comment]
iteresting , what board are you using?

**Comment by arihantdaga** [comment]
ESP8266 12E

**Comment by spaniakos** [comment]
as expected.
there is a bug with ESP8266.
I bought mine a couple fo days ago, but i am leaving for vacation in some
days.

by the end of august i will fully support ESP8266

**Comment by arihantdaga** [comment]
@spaniakos Any Updates on it bro ?

**Comment by spaniakos** [comment]
Sunday i finish my vacations. Shortly after i will publish an update.

**Comment by arihantdaga** [comment]
Is there a formula to predict max cipher size for a given length of message ?
For example if in the following code i dont have to use buffer of size 1000 instead i can allocate buffer based on the msg size. ? 
 
`void encryptMsg(const char* msg, char data_encoded[],char iv_encoded[]){

    char b64data[200];
    byte cipher[1000];
....
...
}

`

**Comment by yhua537** [comment]
AES has the same size of input and output.

**Comment by arihantdaga** [comment]
@yhua537 What do u mean by size of input and output.. ?
Input and out to do_aes_encrypt() or do_aes_decrypt() ? 
Can u explain ur situation better ?

**Comment by spaniakos** [comment]
I would need a sample code and output in order to comment on that.

Thank you

**Comment by arihantdaga** [comment]
Any Update on the this... ? 
The issue still persists...

**Comment by arihantdaga** [comment]
I think the issue is somewhat with the code only..
Closing for now..

**Comment by spaniakos** [comment]
no updates as i am still traveling for some work...
There have been some long months, but by the end of the week i return to my
base station (Home)!
:D thank you for your patience.
