### ISSUE TITLE
padedLength and time

### ISSUE THREAD

**Issue by PabloGN** [spaniakos/AES#31]
**padedLength  error in aes.pde (Arduino code)**
When plainLength doesn't need to round up (`plainLength % N_BLOCK == 0`) padedLength is greater than plainLength. 

```
int plainLength = sizeof(plain)-1;  // don't count the trailing /0 of the string !
int padedLength = plainLength + N_BLOCK - plainLength % N_BLOCK;
```
```
int padedLength = plainLength;
if (plainLength % N_BLOCK !=0)
     padedLength += N_BLOCK - plainLength % N_BLOCK;
```

** Time measure**
`Serial.println(micros() - ms);` adds the time to send printed string.
It should be:
```
endtime=micros();
Serial.println( endtime - ms);
```

**Comment by spaniakos** [comment]
you are correct about the time , i will fix that.

now about the padded length, even is 
`plainLength % N_BLOCK == 0 `
the standard for encryption on PKCS7 padding with AES CSB is to always pad at least 1 byte.
 if the plaintext is equal to a multiple of N_BLOCK then a full block of padding is added.

[](https://tools.ietf.org/html/rfc2315)
page 21, section 2

**Comment by PabloGN** [comment]
Thank you!
