### ISSUE TITLE
Wrong IV size during print in example

### ISSUE THREAD

**Issue by sunny127** [spaniakos/AES#6]
In file aes.pde line 56, it should be 

aes.printArray(iv,8);

Because the type of IV is 'unsigned long long int' and it is 64 bits, thus 8 bytes. Not 16.

**Comment by spaniakos** [comment]
you are probably correct on this one. i will review after my day-jobs deadline for the current project.

Thank you.

**Comment by spaniakos** [comment]
it's supposed to be 16bytes
as the blocks are 16bytes.

the iv given in transforms to an IV that will be used
as shown to the lines 10 and 11
`//real iv = iv x2 ex: 01234567 = 0123456701234567
unsigned long long int my_iv = 36753562;`
